### ISSUE TITLE
Modify tools/label_from_gdoc() to work with our metadata format

### ISSUE THREAD

**Issue by paulnov** [devdatalab/covid#10]
We have a Stata function `label_from_gdoc()` that pulls labels from an external google sheet. We have standardized google sheets with metadata for this project.

Currently the Stata function doesn't work because it assumes variable is column 1 and label is column 2. We should add optional fields `varcol()` and `labelcol()` to `label_from_gdoc()` so that we can specify column numbers in the call.

**Comment by paulnov** [comment]
(note that it might be faster to just rewrite this in python with regular expressions rather than dealing with Stata's clunky string operators)

**Comment by tobylunt** [comment]
@alison-campion, this issue is related to the problem I was talking with you about yesterday - let's use Python for this, to accomplish both pulling down variable labels as well as retrieving the variable collapse mechanism we'll use for converting from PC11 to LGD.
