### ISSUE TITLE
Get ICU beds and Oxygen availability from DLHS into district collapse

### ISSUE THREAD

**Issue by paulnov** [devdatalab/covid#14]
This means modifying `prep_dlhs4_district.do` to add a bunch of variables to each of the collapses. Note this file has 3 components— district hospitals (dh), community health centers (chc), primary health centers (phc). Each of these has a slightly different survey, so you’ll have to examine the closest thing in there to intensive care beds and oxygen availability. A useful stata tool is `lookfor`, which searches the varlist and descriptions.

We won’t have ICU beds in all data sets— looks like we have ICU in the district hospital dataset, and presence of oxygen (probably tanks) in the chc and phc. But scroll through the variable lists and see if there’s anything comparable that could be a good indicator of capability of treating pneumonia.

Don’t create a variable combining these across all the datasets— not really feasible since e.g. DH records number ICU beds, while the other clinics just report presence of O2.

Prefix the variables following the convention in the code (e.g. dh_ for district hospitals), and give descriptive variable names and labels.

**Comment by tobylunt** [comment]
This is done, right @pranit-gupta?
